export {  loader } from './loader'
export { Home } from './home'
export { default as Read } from './read'
export { default as Products } from './products'
export { default as Footer } from './footer'
export { default as Event } from './event'
