export {  default as loader } from './loader'
export { Home } from './home'
export { default as Login } from './login'
export { default as Read } from './read'
export { default as Products } from './products'
export { default as Footer } from './footer'
export { default as Event } from './event'
export { default as Donation } from './donation'
export { default as Blog } from './blog'
export { default as Fespace } from './fespace'